### PR TITLE
use niv to manage nixpkgs pinning etc

### PR DESCRIPTION
**Pull request by adamse**

### CODE REVIEW

**Comment by adamse** [comment]
@lazamar please take a look as well

**Comment by adamse** [comment]
Probably want to bump the ghcide version, 0.2.0 in this pin for ghc 883.

**Comment by pepeiborra** [comment]
> Probably want to bump the ghcide version, 0.2.0 in this pin for ghc 883.

ghcide 0.2.0 is good enough for me

**Comment by pepeiborra** [comment]
Nice, thanks!

**Pull request merged**
