### PR TITLE
Continuous integration automation

### PR DESCRIPTION
**Pull request by vapourismo**
1. Configure HLint and fix some issues it highlighted
2. GitHub workflow which builds and tests
3. Small fix to bring `hspec-discover` into scope for test discovery

### CODE REVIEW

**Comment by vapourismo** [comment]
cc @adamse @pepeiborra

**Comment by adamse** [comment]
Anything that had to be done for github ci to kick in?

**Comment by vapourismo** [comment]
It is automatic. As you might have seen by now :)

**Comment by adamse** [comment]
Looks like github-ci changed something https://github.com/pepeiborra/schemas/issues/21

**Pull request merged**
